-- The one row the setup wizard writes and the app and worker read. Secrets are encrypted with ENCRYPTION_KEY.
CREATE TABLE IF NOT EXISTS instance_settings (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  setup_completed INTEGER NOT NULL DEFAULT 0,
  instance_name TEXT,
  app_url TEXT,
  timezone TEXT,
  admin_email TEXT,
  allow_signups INTEGER NOT NULL DEFAULT 0,
  agent_ai_provider TEXT,
  agent_ai_key_encrypted TEXT,
  agent_ai_model_fast TEXT,
  agent_ai_model_writer TEXT,
  agent_daily_cap_usd REAL NOT NULL DEFAULT 1.0,
  account_monthly_cap_usd REAL NOT NULL DEFAULT 12.0,
  proxy_provider TEXT NOT NULL DEFAULT 'none',
  proxy_seller_key_encrypted TEXT,
  email_provider TEXT NOT NULL DEFAULT 'none',
  email_key_encrypted TEXT,
  smtp_host TEXT,
  smtp_port INTEGER,
  smtp_user TEXT,
  smtp_password_encrypted TEXT,
  smtp_tls INTEGER NOT NULL DEFAULT 1,
  email_from_name TEXT,
  email_from_address TEXT,
  storage_provider TEXT NOT NULL DEFAULT 'local',
  s3_endpoint TEXT,
  s3_region TEXT,
  s3_bucket TEXT,
  s3_access_key_encrypted TEXT,
  s3_secret_encrypted TEXT,
  s3_public_url TEXT,
  cron_secret_encrypted TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
INSERT OR IGNORE INTO instance_settings (id, created_at, updated_at) VALUES (1, strftime('%s','now'), strftime('%s','now'));
